services:
  mosquitto:
    ports:
      - "8884:8884"

  simulator-uci:
    environment:
      MQTT_PORT: "8884"
      MQTT_USERNAME: "iot_uci_01"
      MQTT_PASSWORD_FILE: "/run/secrets/simulator/api_key"

  simulator-urgencias:
    environment:
      MQTT_PORT: "8884"
      MQTT_USERNAME: "iot_urgencias_01"
      MQTT_PASSWORD_FILE: "/run/secrets/simulator/api_key"

  simulator-laboratorio:
    environment:
      MQTT_PORT: "8884"
      MQTT_USERNAME: "iot_laboratorio_01"
      MQTT_PASSWORD_FILE: "/run/secrets/simulator/api_key"

  key-rotator:
    environment:
      BROKER_AUTH_FILE: "/broker-config/passwd-api-key-piloto"
      BROKER_AUTH_DEVICE_MAP: >-
        iot_uci_01=iot_uci_01,
        iot_urgencias_01=iot_urgencias_01,
        iot_laboratorio_01=iot_laboratorio_01
    volumes:
      - ./broker/config:/broker-config

  mosquitto-auth-reloader:
    image: alpine:3.20
    container_name: iot-mosquitto-auth-reloader

    pid: "service:mosquitto"
    network_mode: "none"

    depends_on:
      mosquitto:
        condition: service_started

    user: "0:0"

    cap_drop:
      - ALL

    cap_add:
      - KILL

    security_opt:
      - no-new-privileges:true

    read_only: true
    restart: always

    volumes:
      - type: bind
        source: ./broker/config
        target: /watch
        read_only: true

    command:
      - /bin/sh
      - -c
      - |
        FILE=/watch/passwd-api-key-piloto

        while [ ! -s "$$FILE" ]; do
          echo "[reloader] esperando credenciales"
          sleep 1
        done

        LAST="$$(sha256sum "$$FILE" | cut -d' ' -f1)"

        echo "[reloader] vigilando credenciales piloto"

        while sleep 2; do
          CURRENT="$$(sha256sum "$$FILE" | cut -d' ' -f1)"

          if [ "$$CURRENT" != "$$LAST" ]; then
            kill -HUP 1
            LAST="$$CURRENT"

            echo "[reloader] SIGHUP enviado a Mosquitto"
          fi
        done
